name: Load Test with K6

on: [push]

jobs:
  load-test:
    runs-on: ubuntu-latest
    environment: dev
    #permissions:
    #  actions: read
    #  contents: write
    #  id-token: write # needed for GitHub OIDC token for AWS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up K6
        uses: grafana/setup-k6-action@v1

      # Print environment variables to debug
      - name: Print environment variables
        run: echo "AWS_REGION=$AWS_REGION AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"

      - name: Run K6 script
        uses: grafana/run-k6-action@v1
        with:
          path: ./k6-scripts/load-test.js
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}